# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


# Create new goods
POST http://localhost:1323/api/v1/goods
Content-Type: application/json

{
  "goods_code_name": "0001",
  "goods_title": "Плющевый медведь",
  "goods_description": "Милый плющевый медведь",
  "goods_price": 255.50
}

###
# Get goods list
GET http://localhost:132/api/v1/goods
Accept: application/json

###
# Get goods by id (UUID)
GET http://localhost:1323/api/v1/goods/c26e7e02-c1de-465d-88ff-b845abdc47f1
Accept: application/json

###